#!/usr/bin/env python3
"""Generate the LIPIcs (SEA-format) build of the paper from paper/main.tex.

paper/main.tex stays the single source of the text. This script lifts its title, abstract and
body into the LIPIcs v2021 class and writes paper/sea/main.tex, so the two builds cannot drift.

  scripts/make_lipics.py            anonymous build for double-blind review (default)
  scripts/make_lipics.py --named    with author block, for the proceedings version
  scripts/make_lipics.py --arxiv    with author block, no line numbers, no LIPIcs branding

The output follows Dagstuhl's LIPIcs author rules (https://submission.dagstuhl.de/series/details/LIPIcs):
class defaults untouched (line numbers stay on for review), plain \\cite with the plainurl style
and no natbib, run-in bold headings turned into \\subparagraph*, and the generated number and
table-row macros expanded in place so the article is one file plus its figures.

The anonymous build removes the author block and the sentence linking the public crate. It does
NOT scrub the text for other identifying details; read the output before submitting.
The class files in paper/sea/ are the unmodified Dagstuhl author package v2021.1.3 (LPPL).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "paper" / "main.tex"
OUT = ROOT / "paper" / "sea" / "main.tex"


def between(s, a, b):
    i = s.index(a) + len(a)
    return s[i:s.index(b, i)]


def main():
    arxiv = "--arxiv" in sys.argv
    named = arxiv or "--named" in sys.argv
    s = SRC.read_text()
    title = " ".join(between(s, "\\title{", "}\n\\author").replace("\\\\", " ").split())
    abstract = between(s, "\\begin{abstract}", "\\end{abstract}").strip()
    body = between(s, "\\end{abstract}", "\\bibliographystyle")
    appendix = between(s, "\\bibliography{refs}", "\\end{document}").strip()

    def lipics_rules(text):
        # generated macros (paper/tables/*.tex) expanded in place, longest names first
        macros = {}
        for f in sorted((ROOT / "paper" / "tables").glob("*.tex")):
            for name, val in re.findall(r"\\newcommand\{\\(\w+)\}\{(.*?)\}\n(?=\\newcommand|\Z|%)",
                                        f.read_text().rstrip() + "\n", flags=re.S):
                macros[name] = val.replace("%\n", "").strip()
        for name in sorted(macros, key=len, reverse=True):
            text = re.sub(r"\\" + name + r"(\{\})?(?![A-Za-z])", lambda m: macros[name], text)
        # natbib commands -> plain \cite
        text = re.sub(r"\\cite[pt]\{", r"\\cite{", text)
        # run-in bold headings -> the class's own sectioning macro (not inside table rows)
        text = re.sub(r"(?m)^\\textbf\{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\}(?=[ \n])(?![^\n]*&)",
                      r"\\subparagraph*{\1}", text)
        return text
    preamble_inputs = re.findall(r"^\\input\{tables/[^}]+\}$", s[:s.index("\\begin{document}")], flags=re.M)

    body = body.replace("\\newtheorem{proposition}{Proposition}\n", "")  # LIPIcs defines it
    body = body.replace("\\input{tables/bloom_gap}\n", "")
    acks = between(body, "\\begin{acks}", "\\end{acks}").strip()
    body = body[:body.index("\\begin{acks}")].rstrip() + "\n"
    if not named:
        # drop the sentence that names and links the public implementation
        acks = re.sub(r" \(\\url\{https://github\.com/integrallis/pleated-ribbon-construction\}\)", "", acks)
        acks = re.sub(r"A production implementation.*?\\url\{[^}]*\}\.", 
                      "A production implementation exists; its link is withheld for double-blind review.",
                      acks, flags=re.S)
    body, appendix, abstract, acks = (lipics_rules(x) for x in (body, appendix, abstract, acks))
    options = "a4paper,UKenglish,cleveref,autoref,thm-restate" + ("" if named else ",anonymous")
    author = ("\\author{Brian Sam-Bodden}{Integrallis Software, Scottsdale, Arizona, USA}{bsbodden@integrallis.com}{https://orcid.org/0009-0007-4515-1979}{}\n"
              "\\authorrunning{B. Sam-Bodden}\n\\Copyright{Brian Sam-Bodden}\n")
    if not named:  # keep personal details out of the anonymous source as well as its PDF
        author = ("\\author{Anonymous Author}{Anonymous Affiliation}{}{}{}\n"
                  "\\authorrunning{Anonymous}\n\\Copyright{Anonymous}\n")
    relatedversion = ("\\relatedversion{Preprint: \\url{https://doi.org/10.5281/zenodo.23222458}}\n"
                      if named else "")
    head = f"""% GENERATED by scripts/make_lipics.py from paper/main.tex — edit that file, not this one.
\\documentclass[{options}]{{lipics-v2021}}
\\usepackage{{booktabs}}
\\graphicspath{{{{../}}}}
\\bibliographystyle{{plainurl}}
\\title{{{title}}}
\\titlerunning{{Pleated Ribbon Construction}}
{author}\\ccsdesc[500]{{Theory of computation~Data structures design and analysis}}
\\ccsdesc[300]{{Information systems~Data structures}}
\\keywords{{ribbon filter, approximate membership, filter construction, cache locality, algorithm engineering}}
\\supplement{{Raw measurements, registered protocols and analysis scripts accompany the submission.}}
{relatedversion}""" + ("\\nolinenumbers\n\\hideLIPIcs\n" if arxiv else "") + """\\begin{document}
\\maketitle
\\begin{abstract}
""" + abstract + """
\\end{abstract}
"""
    tail = ("\n\\paragraph*{Artifacts.}\n" + acks + "\n\n\\bibliography{refs}\n\n" + appendix
            + "\n\\end{document}\n")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(head + body + tail)
    # BibTeX refuses a database in a parent directory, so keep a generated copy beside the build.
    (OUT.parent / "refs.bib").write_text(
        "% GENERATED copy of paper/refs.bib by scripts/make_lipics.py - edit that file, not this one.\n"
        + (ROOT / "paper" / "refs.bib").read_text())
    print(f"wrote {OUT.relative_to(ROOT)} ({'arXiv' if arxiv else 'named' if named else 'anonymous'})")


if __name__ == "__main__":
    main()
