#!/usr/bin/env python3
"""Generate the LIPIcs (SEA-format) build of the paper from paper/main.tex.

paper/main.tex stays the single source of the text. This script lifts its title, abstract and
body into the LIPIcs v2021 class and writes paper/sea/main.tex, so the two builds cannot drift.

  scripts/make_lipics.py            anonymous build for double-blind review (default)
  scripts/make_lipics.py --named    with author block, for a proceedings or arXiv version

The anonymous build removes the author block and the sentence linking the public crate. It does
NOT scrub the text for other identifying details; read the output before submitting.
The class files in paper/sea/ are the unmodified Dagstuhl author package v2021.1.3 (LPPL).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "paper" / "main.tex"
OUT = ROOT / "paper" / "sea" / "main.tex"


def between(s, a, b):
    i = s.index(a) + len(a)
    return s[i:s.index(b, i)]


def main():
    named = "--named" in sys.argv
    s = SRC.read_text()
    title = " ".join(between(s, "\\title{", "}\n\\author").replace("\\\\", " ").split())
    abstract = between(s, "\\begin{abstract}", "\\end{abstract}").strip()
    body = between(s, "\\end{abstract}", "\\bibliographystyle")
    appendix = between(s, "\\bibliography{refs}", "\\end{document}").strip()
    appendix = appendix.replace("\\input{tables/", "\\input{../tables/")
    preamble_inputs = re.findall(r"^\\input\{tables/[^}]+\}$", s[:s.index("\\begin{document}")], flags=re.M)

    body = body.replace("\\newtheorem{proposition}{Proposition}\n", "")  # LIPIcs defines it
    body = body.replace("\\input{tables/", "\\input{../tables/")
    acks = between(body, "\\begin{acks}", "\\end{acks}").strip()
    body = body[:body.index("\\begin{acks}")].rstrip() + "\n"
    if not named:
        # drop the sentence that names and links the public implementation
        acks = re.sub(r"A production implementation.*?\\url\{[^}]*\}\.", 
                      "A production implementation exists; its link is withheld for double-blind review.",
                      acks, flags=re.S)
    options = "a4paper,UKenglish,cleveref,autoref,thm-restate" + ("" if named else ",anonymous")
    author = ("\\author{Brian Sam-Bodden}{Integrallis Software}{}{}{}\n"
              "\\authorrunning{B. Sam-Bodden}\n\\Copyright{Brian Sam-Bodden}\n")
    head = f"""% GENERATED by scripts/make_lipics.py from paper/main.tex — edit that file, not this one.
\\documentclass[{options}]{{lipics-v2021}}
\\usepackage{{booktabs}}
\\graphicspath{{{{../}}}}
% the source uses natbib commands; LIPIcs uses plain numeric \\cite
\\newcommand{{\\citep}}[1]{{\\cite{{#1}}}}
\\newcommand{{\\citet}}[1]{{\\cite{{#1}}}}
\\bibliographystyle{{plainurl}}
\\title{{{title}}}
{author}\\ccsdesc[500]{{Theory of computation~Data structures design and analysis}}
\\ccsdesc[300]{{Information systems~Data structures}}
\\keywords{{ribbon filter, approximate membership, filter construction, cache locality, algorithm engineering}}
\\supplement{{Raw measurements, registered protocols and analysis scripts accompany the submission.}}
\\nolinenumbers
\\hideLIPIcs
""" + "\n".join(i.replace("tables/", "../tables/") for i in preamble_inputs) + """
\\begin{document}
\\maketitle
\\begin{abstract}
""" + abstract + """
\\end{abstract}
"""
    tail = ("\n\\paragraph*{Artifacts.}\n" + acks + "\n\n\\bibliography{../refs}\n\n" + appendix
            + "\n\\end{document}\n")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(head + body + tail)
    print(f"wrote {OUT.relative_to(ROOT)} ({'named' if named else 'anonymous'})")


if __name__ == "__main__":
    main()
