#!/usr/bin/env python3
"""Generate paper/main.md, a Markdown rendition of paper/main.tex, with pandoc.

paper/main.tex stays the single source of the text; edit that file and rerun this script.
Requires pandoc and pdftoppm (poppler). Figures are rasterized to paper/figures/*.png so the
Markdown renders without a PDF viewer. Citations are resolved by pandoc's citeproc in its
default author-date style, so they read "(Author Year)" where the PDF has numbers.
"""
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper"
OUT = PAPER / "main.md"


def pandoc(args, text=None):
    return subprocess.run(["pandoc", *args], input=text, capture_output=True, text=True,
                          check=True, cwd=PAPER).stdout


def simplify_math(s):
    s = s.replace("$`\\times`$", "×").replace("$`\\pm`$", "±").replace("$`\\to`$", "→")
    s = re.sub(r"\$`\\mathbf\{([\d.]+)\\pm ?([\d.]+)\}`\$", r"**\1 ± \2**", s)
    s = re.sub(r"\$`([\d.]+)\\pm ?([\d.]+)`\$", r"\1 ± \2", s)
    s = re.sub(r"\$`([\d.]+)\\pm ?([\d.]+) \\to ([\d.]+)\\pm ?([\d.]+)`\$", r"\1 ± \2 → \3 ± \4", s)
    s = re.sub(r"\$`([\d.]+)\\times`\$", r"\1×", s)
    return re.sub(r"\$`([^`]*)`\$", r"$\1$", s)  # remaining math: plain $...$


def strip_tags(s):
    return re.sub(r"<[^>]+>", "", s)


def main():
    tex = (PAPER / "main.tex").read_text()
    title = " ".join(re.search(r"\\title\{(.*?)\}\n\\author", tex, re.S).group(1)
                     .replace("\\\\", " ").split())
    abstract = pandoc(["-f", "latex", "-t", "gfm", "--wrap=none"],
                      re.search(r"\\begin\{abstract\}(.*?)\\end\{abstract\}", tex, re.S).group(1))
    body = pandoc(["main.tex", "-f", "latex", "-t", "gfm", "--citeproc", "--bibliography",
                   "refs.bib", "--wrap=none"])

    # cross-references: keep the resolved number, drop the HTML anchor
    body = re.sub(r'<a href="#[^"]*" data-reference-type="ref" data-reference="[^"]*">([^<]*)</a>',
                  r"\1", body)

    # figures: rasterize and replace the <figure> block
    nfig = 0

    def figure(m):
        nonlocal nfig
        nfig += 1
        pdf = m.group(1)
        png = pdf[:-4] + ".png"
        subprocess.run(["pdftoppm", "-r", "160", "-png", "-singlefile", str(PAPER / pdf),
                        str(PAPER / pdf[:-4])], check=True)
        return f"![Figure {nfig}]({png})\n\n**Figure {nfig}.** {strip_tags(m.group(2)).strip()}"

    body = re.sub(r'<figure id="[^"]*">\s*<embed src="([^"]+)"[^>]*/>\s*<figcaption>(.*?)</figcaption>\s*</figure>',
                  figure, body, flags=re.S)

    # tables: the paragraph after each table is its caption
    lines, out, ntab, i = body.split("\n"), [], 0, 0
    while i < len(lines):
        out.append(lines[i])
        if lines[i].startswith("|") and (i + 1 >= len(lines) or not lines[i + 1].startswith("|")):
            if i + 2 < len(lines) and lines[i + 1] == "" and lines[i + 2] and not lines[i + 2].startswith(("#", "|", "<", "!")):
                ntab += 1
                out += ["", f"**Table {ntab}.** {lines[i + 2]}"]
                i += 2
        i += 1
    body = "\n".join(out)

    body = re.sub(r" ?\{#tab:[^}]*\}", "", body)  # leftover table labels

    # proposition wrapper, acknowledgements heading, reference list
    body = re.sub(r'<div id="prop:[^"]*" class="proposition">\n\n(.*?)\n\n</div>', r"\1", body, flags=re.S)
    body = body.replace("#### Artifacts.", "# Artifacts")
    refs_at = body.index('<div id="refs"')
    refs = [strip_tags(e).strip() for e in
            re.findall(r'<div id="ref-[^"]*" class="csl-entry">(.*?)</div>', body[refs_at:], re.S)]
    body = body[:refs_at].rstrip() + "\n\n# References\n\n" + "\n".join(f"- {r}" for r in refs) + "\n"

    # number sections as in the PDF (1..n, then appendix A, B, C) and demote one level
    nsec, sub, napp, in_app, out = 0, 0, 0, False, []
    for line in body.split("\n"):
        if line.startswith("# "):
            name = line[2:]
            if name in ("Artifacts", "References"):
                out.append("## " + name)
                in_app = name == "Artifacts" or in_app
            elif in_app:
                napp += 1
                out.append(f"## Appendix {chr(64 + napp)}. {name}")
            else:
                nsec, sub = nsec + 1, 0
                out.append(f"## {nsec} {name}")
        elif line.startswith("## "):
            sub += 1
            out.append(f"### {nsec}.{sub} {line[3:]}")
        else:
            out.append(line)
    body = "\n".join(out)
    # pandoc numbers appendix sections after the last main section; the PDF letters them
    body = re.sub(r"Appendix[ \u00a0](\d+)", lambda m: "Appendix " + chr(64 + int(m.group(1)) - nsec), body)

    md = (f"<!-- GENERATED by scripts/make_markdown.py from paper/main.tex. Edit that file, not this one. -->\n\n"
          f"# {title}\n\nBrian Sam-Bodden, Integrallis Software\n\n## Abstract\n\n{abstract.strip()}\n\n"
          + body)
    OUT.write_text(simplify_math(md).rstrip() + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {nfig} figures, {ntab} tables, {len(refs)} references")


if __name__ == "__main__":
    main()
